package fr.modele.ressource;

public enum ERessourceJoueur {
	RESSOURCE_BASE,
	RESSOURCE_NOURRITURE,
	RESSOURCE_EAU,
	RESSOURCE_BOIS,
	RESSOURCE_MINERAI,
	RESSOURCE_PIERRE,
	RESSOURCE_UNITE,
	RESSOURCE_UNITE_EXPLORATION,
	RESSOURCE_UNITE_CONSTRUCTION,
	RESSOURCE_UNITE_DEFENSE;
}
